steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
    - 'VITE_FIREBASE_API_KEY: $$FIREBASE_API_KEY'
    - 'VITE_FIREBASE_APP_ID: $$FIREBASE_APP_ID'
    - 'VITE_FIREBASE_RTDB_URL: https://hub-playground-default-rtdb.europe-west1.firebasedatabase.app'
    - 'VITE_FIREBASE_PROJECT_ID: hub-playground'
  - name: 'node'
    entrypoint: 'npm'
    args: ['test']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
      env: 'FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID'
